### ISSUE TITLE
Lagom and K8 guide error

### ISSUE THREAD

**Issue by guizmaii** [typesafehub/prod-suite-management-doc#10]
Hi,

I think there's something that is not correct in the Lagom and k8 guide.

You talk about a `deploy/kubernetes/scripts/kubectl-wait-for-pods` script but it doesn't exists in the https://github.com/lagom/activator-lagom-java-chirper example.

Instead, we can find a bash function named `wait-for-pods` in the `install`  script here: https://github.com/lagom/activator-lagom-java-chirper/pull/70/files#diff-5512ad8cff21e26389bd1ac642e36301R107

**Comment by longshorej** [comment]
Thanks @guizmaii - we just created a PR to fix this. I'll close this out when it is merged: https://github.com/lagom/activator-lagom-java-chirper/pull/76

Thanks for bringing it to our attention!
