### ISSUE TITLE
Seed nodes can't resolve each other

### ISSUE THREAD

**Issue by bantonsson** [typesafehub/prod-suite-management-doc#20]
Hi,

I tried to use this guide as a staring point for a runnable template for Rogers using Minikube, but the seed nodes couldn't resolve each other. It seems that you have to have a "bind host", the actual host to bind to, and a "logical host", that the other nodes can resolve.

You would need this in the `build.sbt`

```
      """-Dakka.remote.netty.tcp.hostname="$AKKA_REMOTING_LOGICAL_HOST"""",
      """-Dakka.remote.netty.tcp.port="$AKKA_REMOTING_BIND_PORT"""",
      """-Dakka.remote.netty.tcp.bind-hostname="$AKKA_REMOTING_BIND_HOST"""",
      """-Dakka.remote.netty.tcp.bind-port="$AKKA_REMOTING_BIND_PORT"""",
```

The bind host is the `pod_host_name`, and the logical host is the `pod_host_name.service_name`.

I also looked at another sample project for using the StatefulSet, and they used this exact pattern for the names of the pods.

Does this sound familiar, or am I doing something wrong?

**Comment by longshorej** [comment]
Hey @bantonsson,

Was this the Akka K8s guide or the Lagom one? I'm surprised you'd need to separate the two as Kubernetes networking is different than Docker (K8s doesn't use NAT to talk to other containers), but I'm happy to investigate further.

**Comment by bantonsson** [comment]
Hey, sorry for missing that information. It was the Akka K8s guide.

So I'm pretty sure that since my pods are running docker Images, there is virtual networking involved, but that's beside the point. The problem arises because the pods can't resolve the other pods name via name lookup, so it can't know which IP address to connect to.

Here is a log where I attach to one of the seed pods, and try to ping another of the seed pods. My pods in the stateful set are named `sharding-sample-seeds-X`, `s3-X` for short, and the service is named `seeds-remoting`. As you can see, `s3-0` can't ping `s3-1` since it can't resolve that host name, but it can ping `s3-1.seeds-remoting`.

```
ban-mbp:akka-sample-sharding-k8s-java@master» kubectl exec -ti sharding-sample-seeds-0 -- bash

daemon@sharding-sample-seeds-0:/opt/docker$ ping sharding-sample-seeds-0
PING sharding-sample-seeds-0.seeds-remoting.default.svc.cluster.local (172.17.0.4): 56 data bytes
64 bytes from 172.17.0.4: icmp_seq=0 ttl=64 time=0.049 ms
64 bytes from 172.17.0.4: icmp_seq=1 ttl=64 time=0.038 ms
^C--- sharding-sample-seeds-0.seeds-remoting.default.svc.cluster.local ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.038/0.043/0.049/0.000 ms

daemon@sharding-sample-seeds-0:/opt/docker$ ping sharding-sample-seeds-1
ping: unknown host

daemon@sharding-sample-seeds-0:/opt/docker$ ping sharding-sample-seeds-1.seeds-remoting
PING sharding-sample-seeds-1.seeds-remoting.default.svc.cluster.local (172.17.0.5): 56 data bytes
64 bytes from 172.17.0.5: icmp_seq=0 ttl=64 time=0.055 ms
64 bytes from 172.17.0.5: icmp_seq=1 ttl=64 time=0.068 ms
64 bytes from 172.17.0.5: icmp_seq=2 ttl=64 time=0.055 ms
^C--- sharding-sample-seeds-1.seeds-remoting.default.svc.cluster.local ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.055/0.059/0.068/0.000 ms
```

**Comment by longshorej** [comment]
Ah, I think that's a mistake in the guide, sorry about that! The environment variable values for `AKKA_SEED_NODE_HOST_{1,2,3}` should contain the service name as well, so when you [create the StatefulSet](http://tech-hub.lightbend.com/guides/k8-akka-cluster/#5-creating-a-kubernetes-statefulset-resource) the env variables should be:

`$statefulsetname-$number.$servicename.default.svc.cluster.local`

As you found out, it should be `sharding-sample-seeds-0.seeds-remoting.default.svc.cluster.local` in your case.

If you can verify that works for you, I'll update the guide. I don't expect that you'll need to set `bind-hostname`, simply setting `hostname` should be enough. See also [this line in Chirper](https://github.com/lagom/activator-lagom-java-chirper/blob/master/friend-impl/pom.xml#L92).

Also, just to expand on my comment earlier, the K8s and Docker networking models are a bit different - https://kubernetes.io/docs/concepts/cluster-administration/networking/ expands on that.

**Comment by bantonsson** [comment]
Yes, the `$statefulsetname-$number.$servicename` is enough for my sample to work fine.

You are also right that both that name and the `$statefulsetname-$number` resolves to the same ip, so I shouldn't need the `bind-hostname`. Don't know why I came to the conclusion that I needed that. I'll experiment with removing it tomorrow.

**Comment by bantonsson** [comment]
I knew there was a reason that I had used the bind-host. When I tried to only use the `$statefulsetname-$number.$servicename` I got this exception from way down in `java.net.*` when starting up remoting and Netty.

```
Exception in thread "main" java.net.UnknownHostException: sharding-sample-seeds-0.seeds-remoting: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at akka.remote.transport.netty.NettyTransport.$anonfun$addressToSocketAddress$2(NettyTransport.scala:407)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
	at scala.concurrent.package$.blocking(package.scala:142)
	at akka.remote.transport.netty.NettyTransport.$anonfun$addressToSocketAddress$1(NettyTransport.scala:407)
```

**Comment by bantonsson** [comment]
I've pushed my sample here https://github.com/bantonsson/akka-sample-sharding-k8s-java

**Comment by longshorej** [comment]
Thanks - I put a PR up - https://github.com/bantonsson/akka-sample-sharding-k8s-java/pull/1

If you use the FQDN for the service the JDK doesn't throw that exception. I can only assume they aren't checking search domains for some reason, note the following resolv.conf:

```bash
$ kubectl exec sharding-sample-seeds-0 -- /bin/cat /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
-> 0

```

**Comment by bantonsson** [comment]
The JDK moves in mysterious ways. Thanks for the fix.

**Comment by lubinson** [comment]
Hi @bantonsson @longshorej 

I have same problem even using a full FQDN. Exception as below:
```
[WARN] [09/04/2018 16:09:27.499] [MySharding-akka.remote.default-remote-dispatcher-4] 
[akka.tcp://MySharding@myservice-seed-0.myservice-
seed.default.svc.cluster.local:2551/system/endpointManager/reliableEndpointWriter-
akka.tcp%3A%2F%2FMySharding%40myservice-seed-2.myservice-seed.default.svc.cluster.local%3A2551-
2] Association with remote system [akka.tcp://MySharding@myservice-seed-2.myservice-
seed.default.svc.cluster.local:2551] has failed, address is now gated for [5000] ms. Reason: [Association 
failed with [akka.tcp://MySharding@myservice-seed-2.myservice-seed.default.svc.cluster.local:2551]] 
Caused by: [myservice-seed-2.myservice-seed.default.svc.cluster.local: Name or service not known]

```
The same code works fine out side k8s using static ip. 

Thanks.
