### ISSUE TITLE
Formatting issues in new deployment guide

### ISSUE THREAD

**Issue by rstento** [typesafehub/prod-suite-management-doc#7]
In the k8s-microservices guide, the formatting is off from the "Deployment" heading on down. Double bullet and number in the high level list and the numbered sections that follow aren't indented.
![image](https://user-images.githubusercontent.com/22889339/29333184-1d16ae7a-81c0-11e7-86d5-438df8f38010.png)

**Comment by longshorej** [comment]
Thanks @rstento - this is fixed. Feel free to reopen if you think it doesn't look quite right.

**Comment by rstento** [comment]
Looks great, Jason, Thanks!

Ruth Stento
User Experience Lead
Lightbend

512-818-6459
<http://lightbend.com>
<https://www.reactivesummit.org/registration?utm_source=email&utm_medium=email-signature&utm_campaign=EVT-2017-OCT-Reactive-Summit-Austin&utm_term=none&utm_content=none>
